# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_py_files": "01_nbutils.ipynb",
         "get_cells_one_nb": "01_nbutils.ipynb",
         "write_code_cell": "01_nbutils.ipynb",
         "py_to_nb": "01_nbutils.ipynb",
         "get_module_text": "01_nbutils.ipynb",
         "write_module_text": "01_nbutils.ipynb",
         "clear_all_modules": "01_nbutils.ipynb",
         "simple_export_one_nb": "01_nbutils.ipynb",
         "simple_export_all_nb": "01_nbutils.ipynb",
         "get_corr": "02_tabutils.ipynb",
         "corr_drop_cols": "02_tabutils.ipynb",
         "rf_feat_importance": "02_tabutils.ipynb",
         "plot_fi": "02_tabutils.ipynb",
         "TabularPandas.export": "02_tabutils.ipynb",
         "load_pandas": "02_tabutils.ipynb",
         "create": "03_Tracking.ipynb",
         "append": "03_Tracking.ipynb",
         "delete": "03_Tracking.ipynb",
         "print_keys": "03_Tracking.ipynb",
         "get_stat": "03_Tracking.ipynb",
         "get_stats": "03_Tracking.ipynb",
         "print_best": "03_Tracking.ipynb",
         "graph_stat": "03_Tracking.ipynb",
         "graph_stats": "03_Tracking.ipynb",
         "run_bash": "04_kaggle.ipynb",
         "update_datset": "04_kaggle.ipynb",
         "create_dataset": "04_kaggle.ipynb",
         "download_dataset_metadata": "04_kaggle.ipynb",
         "download_dataset_content": "04_kaggle.ipynb",
         "download_dataset": "04_kaggle.ipynb",
         "add_library_to_dataset": "04_kaggle.ipynb",
         "bin_df": "05_splitting.ipynb",
         "kfold_Stratified_df": "05_splitting.ipynb"}

modules = ["nbutils.py",
           "tabutils.py",
           "tracking.py",
           "kaggle.py",
           "splitting.py"]

doc_url = "https://Isaac.Flath@gmail.com.github.io/perutils/"

git_url = "https://github.com/Isaac.Flath@gmail.com/perutils/tree/{branch}/"

def custom_doc_links(name): return None
